issues:
  exclude-dirs:
    - vendor
  modules-download-mode: vendor

linters:
  disable-all: true #so that lint version bumps don't change results
  enable:
    - copyloopvar
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nosprintfhostport
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - usetesting
    - wastedassign